#pragma config(Sensor, S3,     reflectedValue, sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define LEFT_MOTOR motorB
#define RIGHT_MOTOR motorC

#define BLUE 2
#define GREEN 3
#define YELLOW 4
#define RED 5

task main()  {

	if (SensorValue(reflectedValue) == RED){
		motor[LEFT_MOTOR] = +30; motor[RIGHT_MOTOR] = +30;
		wait1Msec(1000);
	}

	if (SensorValue(reflectedValue) == BLUE){
		motor[LEFT_MOTOR] = 0; motor[RIGHT_MOTOR] = +47;
		wait1Msec(750);
		motor[LEFT_MOTOR] = +30; motor[RIGHT_MOTOR] = +30;
		wait1Msec(500);
	}

	if (SensorValue(reflectedValue) == YELLOW){
		motor[LEFT_MOTOR] = +47; motor[RIGHT_MOTOR] = 0;
		wait1Msec(750);
		motor[LEFT_MOTOR] = +30; motor[RIGHT_MOTOR] = +30;
		wait1Msec(500);
	}

	if (SensorValue(reflectedValue) == GREEN){
		motor[LEFT_MOTOR] = -30; motor[RIGHT_MOTOR] = -30;
		wait1Msec(1000);
	}
}
