#pragma config(Sensor, S4,     ultra,          sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int value;

	while ( 1 ){
		value = SensorValue( ultra );
		displayTextLine( 0, "%d cm", value );

		if ( value > 30 ) { motor[ motorB ] = abs(value-30); motor[ motorC ] = abs(value-30); }
		else if ( value < 30 ) { motor[ motorB ] = -abs(value-30); motor[ motorC ] = -abs(value-30); }
		else { motor[ motorB ] = 0; motor[ motorC ] = 0; }
	}
}
